Dz3 mainpage
js-tasks-ru/htmlcss-20241107_panteleev-alexander pull request #3
Opened 2024-11-24 15:14 UTC by alexandrpanteleev

Добрый день! Заверстал главную страницу отчасти уже опираясь на лекцию от 14.11.2024. В качестве нормалайза выбрал destyle.css, добавив к нему от себя удаление margin в недостающих тегах. Выбрал его, потому что он в целом устроен как нормалайз и не сбрасывает лишнего, при этом есть бордер-бокс и удалены margin.

2024-11-24 15:15 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-26 15:56 UTC, GSemikozov requested changes

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 384px;
лишнее ограничение

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +.footer-title {
.footer__title

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 111px;
ширину и высоту не надо ограничивать

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title-position {
а зачем вот эти элементы с position? кажется это лишнее

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +.footer-description {
.footer__description

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 640px;
max-width

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 96px;
лишнее

2024-11-26 15:56 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__description-position {
лишнее (нужен отступ - на уровне элемента)

2024-11-26 15:56 UTC, GSemikozov commented on components/header/header.css
> +    height: 237px;
лишнее

2024-11-26 15:56 UTC, GSemikozov commented on components/header/header.css
> +    padding-top: 96px;
отступ и сверху нужен

2024-11-26 15:56 UTC, GSemikozov commented on components/header/header.css
> +.header-title {
.header__title

2024-11-26 15:56 UTC, GSemikozov commented on components/header/header.css
> +    width: 670px;
ширину и высоту фиксировать не надо

2024-11-26 15:56 UTC, GSemikozov commented on components/page-matter/page-matter.css
> +    gap: 0px;
gap, opacity, height - здесь не надо

2024-11-26 15:56 UTC, GSemikozov commented on components/page/page.css
> +.page__block {
а зачем? это лишнее

2024-11-26 15:56 UTC, GSemikozov commented on components/page/page.css
> +    width: 100%;
лишнее

2024-12-12 14:23 UTC, GSemikozov approved these changes

2024-12-12 14:23 UTC, merged