dz3-button
js-tasks-ru/htmlcss-20241107_panteleev-alexander pull request #4
Opened 2024-11-25 00:20 UTC by alexandrpanteleev

2024-11-25 00:21 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-26 15:59 UTC, GSemikozov requested changes

2024-11-26 15:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-set {
какие-то вспомогательные стили? такие мы не размещаем в файлах стилей компонентов) надо удалить

2024-11-26 15:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
лишнее ограничение

2024-11-26 15:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-bottom: 14px;
по краям тоже нужны (по 16)

2024-11-26 15:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
модификаторы пишутся через `_`

2024-11-26 15:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: background 200ms ease-in-out 100ms;
это пока не надо

2024-11-26 15:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary:disabled {
disabled будет общим для всех кнопок - `.button:disabled { pointer-events: none; opacity: 0.5; }`

2024-11-26 15:59 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                Primary disabled
текста в кнопках надо поправить)

2024-12-08 23:05 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-08 23:17 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-08 23:20 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-09 00:52 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-12 14:23 UTC, GSemikozov submitted a review, later dismissed
есть конфликт, надо поправить. А так - задача принята

2024-12-12 14:24 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-12-25 09:52 UTC, GSemikozov approved these changes

2024-12-25 09:52 UTC, merged